### ISSUE TITLE
running ezaci.py on linux

### ISSUE THREAD

**Issue by Sraza11** [scotttyso/iac-easy-aci#4]
btw, I was getting a directory error when I ran ezaci.py from a Linux box.   I had to use the following command as a workaround. 

```
dos2unix ./ezaci.py

**Comment by scotttyso** [comment]
please show the error.  I use WSL as the development platform, so by default it works in Linux first.

**Comment by Sraza11** [comment]
If I see that error I will open an issue.  Thanks
